<?php
	# generated by EasyPack
	/** @var array $_lang */
	$_lang = array_merge(
		array (
  'setting_lg_theme_auth_bgphoto' => 'Фоновое изображение',
  'setting_lg_theme_auth_bgphoto_desc' => 'В разделе авторизации, фоном будет ваш слайд.',
  'setting_lg_theme_auth_logo' => 'Логотип',
  'setting_lg_theme_auth_logo_desc' => 'Используйте логотип. Либо свой либо клиента. Желательно квадратной формы.',
  'setting_lg_theme_auth_title' => 'Заголовок',
  'setting_lg_theme_auth_title_desc' => 'Приветственный заголовок в разделе авторизации пользователя',
  'setting_lg_theme_auth_txt' => 'Текст',
  'setting_lg_theme_auth_txt_desc' => 'Приветственный текст в разделе авторизации пользователя',
  'setting_lg_theme_auth_web' => 'Ссылка на сайт разработчика.',
  'setting_lg_theme_auth_web_desc' => 'В меню авторизации будет указанна ваша ссылка для напоминания заказчику. Или можете удалить ссылку.',
  'setting_lg_theme_bg_color' => 'Цвет акцента сайта',
  'setting_lg_theme_bg_color_desc' => 'Основной цвет оформления сайта <b>По умолчанию #283593</b>. Оставьте пустым чтобы был по умолчанию',
  'setting_lg_theme_bg_txt_color' => 'Цвет текста',
  'setting_lg_theme_bg_txt_color_desc' => 'Цвет текста сайта. <b>По умолчанию #333</b>',
  'setting_lg_theme_bg_txt_color_ok' => 'Цвет кнопки ОК',
  'setting_lg_theme_bg_txt_color_ok_desc' => 'Может не корректно работать, так как не у всех приложениях имеется class или ID. <b>По умолчанию #6fb61d</b>',
  'setting_lg_theme_font' => 'Шрифт',
  'setting_lg_theme_font_desc' => 'Выберите шрифт:<br/>
<b>1 - Gilroy <br/>
2 - Open Sans<br/>
3 - Roboto</b>',
)
		, $_lang);
	